# Generated by site-kungfu-tech from one exact signed Alpha.2 publication.
# Catalog: sha256:f68536e7050ca5911948db73e34a1ac5c563c27b8e565fc2cd11f34819c2feff
[CmdletBinding()]
param(
  [ValidateSet('alpha')][string]$Channel = 'alpha',
  [string]$Version,
  [string]$InstallDir = (Join-Path $env:LOCALAPPDATA 'Kungfu\product'),
  [string]$CacheDir = (Join-Path $env:LOCALAPPDATA 'Kungfu\cache\installers'),
  [string]$BinDir = (Join-Path $env:LOCALAPPDATA 'Kungfu\bin'),
  [switch]$Rollback,
  [switch]$DryRun,
  [switch]$NoPath,
  [switch]$Yes,
  [switch]$CI
)
$ErrorActionPreference = 'Stop'
$ExactVersion = '4.0.0-alpha.2'
$SourceCommit = 'b0cff8236b8b3746f8028b9d519ed3b0e26096c9'
$CatalogRoot = 'sha256:f68536e7050ca5911948db73e34a1ac5c563c27b8e565fc2cd11f34819c2feff'
$ChannelRoot = '8c031dd420e15ddde5b4e751cb4dcc3c0a2d4bd67956d295918e21165de6abdd'
$ChannelUrl = "https://kungfu.tech/channels/alpha/$ChannelRoot/index.json"
$ChannelSha256 = '8b01d6aab5d71949da2a9ff90f4d05fb725e9338979b52e38454ca653b7ee3ca'
$TrustedKey = 'ed25519-3c473c24ca261745=bNB6syHpgY0RKMHPKUhekyQupwgvtwqQ6qqrUV2ecfQ='
$ReleasePassportRoot = 'sha256:63116c9c3f035025ae0166863cc5ef43dab67dfba153d039a09d428f02dbe2c0'
$RequestedVersion = $Version

function Write-Phase([string]$Name, [string]$Message) {
  Write-Host "kungfu-install: phase[$Name]: $Message"
}
function Fail([string]$Category, [string]$Message) {
  throw "error[$Category]: $Message"
}
function Read-Pointer([string]$Pointer) {
  if (-not (Test-Path -LiteralPath $Pointer -PathType Leaf)) { return $null }
  return (Get-Content -LiteralPath $Pointer -TotalCount 1).Trim()
}
function Test-OwnedVersion([string]$Target) {
  if (-not $Target) { return $false }
  $Versions = [IO.Path]::GetFullPath((Join-Path $InstallDir 'versions'))
  $Full = [IO.Path]::GetFullPath($Target)
  return $Full.StartsWith($Versions + [IO.Path]::DirectorySeparatorChar, [StringComparison]::OrdinalIgnoreCase)
}
function Set-AtomicText([string]$Destination, [string]$Text) {
  $Temporary = "$Destination.$PID.$([Guid]::NewGuid().ToString('N')).tmp"
  [IO.File]::WriteAllText($Temporary, $Text, (New-Object Text.UTF8Encoding($false)))
  Move-Item -Force -LiteralPath $Temporary -Destination $Destination
}
function New-LauncherBytes([string]$Target) {
  $Text = "@rem kungfu-site-managed/v1`r`n@setlocal`r`n@set `"KUNGFU_INSTALL_SOURCE=site-managed-archive`"`r`n@set `"KUNGFU_DIR=$Target\runtime`"`r`n@call `"$Target\kungfu.cmd`" %*`r`n"
  return [Text.Encoding]::ASCII.GetBytes($Text)
}
function Set-AtomicLauncher([string]$Destination, [string]$Target) {
  $Temporary = "$Destination.$PID.tmp"
  [IO.File]::WriteAllBytes($Temporary, (New-LauncherBytes $Target))
  Move-Item -Force -LiteralPath $Temporary -Destination $Destination
}
function Test-OwnedLauncher([string]$Launcher) {
  if (-not (Test-Path -LiteralPath $Launcher)) { return $true }
  if (-not (Test-Path -LiteralPath $Launcher -PathType Leaf)) { return $false }
  return (Get-Content -LiteralPath $Launcher -TotalCount 1) -in @(
    '@rem kungfu-site-managed/v1',
    '@rem kungfu-archive-bootstrap/v1'
  )
}

if ($Channel -ne 'alpha') { Fail 'channel-unavailable' 'this installer is pinned to alpha' }
if ($RequestedVersion -and $RequestedVersion -ne $ExactVersion) {
  Fail 'version-unavailable' "this installer selects exactly $ExactVersion"
}
if (-not [Environment]::Is64BitOperatingSystem) { Fail 'unsupported-platform' '64-bit Windows is required' }
if ([Runtime.InteropServices.RuntimeInformation]::OSArchitecture.ToString() -ne 'x64') {
  Fail 'unsupported-architecture' 'Alpha.2 supports Windows x64 only'
}

$Architecture = 'x64'
$Platform = 'win32'
$ManifestRoot = 'sha256:094448e272594dce2626fb9d4fe893e2608e700c1a86a5463f2bb3f4e2875551'
$ArtifactRoot = 'sha256:cab0d927b4735b583b34a722e963154c44fd1e9b876ae72d389a2942bd5803de'
$ReleaseCutRoot = 'sha256:a755016042e1d724f888d6cb6bd3c6a4650debfe6d80c338c62b56a5783526f1'
$PlatformSliceRoot = 'sha256:c234d8e82f5f3c9868ae5db55f58af6b06c13226dcfa4107696b78a7c0a10c37'
$ArtifactUrl = 'https://github.com/kungfu-systems/kungfu/releases/download/v4.0.0-alpha.2/kungfu-episodes-cli-windows-x64.zip'
$ArtifactSize = [int64]1186367915
$ArtifactDigest = '976aa3b5a7b7ab5525a6d0209dcb6ae77feefa9c68820ffcf4ee18d157c0ed7c'
$ArchiveName = 'kungfu-episodes-cli-windows-x64.zip'
$ArchiveBase = 'kungfu-episodes-cli-windows-x64'
$ArchiveEntries = 2244
$ArchiveLinks = 0
$VersionKey = $ManifestRoot.Substring(7, 16)
$VersionRoot = Join-Path $InstallDir "versions\$ExactVersion-$VersionKey"
$CurrentPointer = Join-Path $InstallDir 'current.path'
$PreviousPointer = Join-Path $InstallDir 'previous.path'
$Launcher = Join-Path $BinDir 'kungfu.cmd'
$ReceiptLine = "catalog=$CatalogRoot version=$ExactVersion source=$SourceCommit manifest=$ManifestRoot artifact=$ArtifactRoot passport=$ReleasePassportRoot"
Write-Phase 'plan' "$Channel $ExactVersion $Platform/$Architecture -> $VersionRoot"
if ($Rollback) { Write-Phase 'plan' "rollback current=$CurrentPointer previous=$PreviousPointer" }
if ($DryRun) { exit 0 }

if (-not (Test-OwnedLauncher $Launcher)) {
  Fail 'ownership-conflict' "$Launcher is not owned by the Kungfu managed installer"
}
$Existing = Get-Command kungfu -ErrorAction SilentlyContinue
if ($Existing -and [IO.Path]::GetFullPath($Existing.Source) -ne [IO.Path]::GetFullPath($Launcher)) {
  Fail 'ownership-conflict' "existing Kungfu is owned outside ${Launcher}: $($Existing.Source)"
}

if ($Rollback) {
  $CurrentTarget = Read-Pointer $CurrentPointer
  $PreviousTarget = Read-Pointer $PreviousPointer
  if (-not (Test-OwnedVersion $CurrentTarget)) { Fail 'rollback-ownership' 'current does not name a managed version' }
  if (-not (Test-OwnedVersion $PreviousTarget)) { Fail 'rollback-unavailable' 'no verified previous version exists' }
  $PreviousReceipt = Join-Path $PreviousTarget 'install\site-managed-receipt'
  $PreviousBootstrapReceipt = Join-Path $PreviousTarget 'install\bootstrap-receipt.json'
  if (
    -not (Test-Path -LiteralPath $PreviousReceipt -PathType Leaf) -or
    (Get-Content -LiteralPath $PreviousReceipt -Raw).TrimEnd() -notmatch '^catalog=sha256:[a-f0-9]{64} version=[^ ]+ source=[a-f0-9]{40} manifest=sha256:[a-f0-9]{64} artifact=sha256:[a-f0-9]{64} passport=sha256:[a-f0-9]{64}$'
  ) { Fail 'rollback-verification' 'previous managed receipt is missing or invalid' }
  try { $PreviousBootstrap = Get-Content -LiteralPath $PreviousBootstrapReceipt -Raw | ConvertFrom-Json }
  catch { Fail 'rollback-verification' 'previous product bootstrap receipt is unreadable' }
  if ($PreviousBootstrap.state -ne 'verified') { Fail 'rollback-verification' 'previous product bootstrap receipt is not verified' }
  $PreviousCommand = Join-Path $PreviousTarget 'kungfu.cmd'
  if (-not (Test-Path -LiteralPath $PreviousCommand -PathType Leaf)) { Fail 'rollback-verification' 'previous Kungfu command is missing' }
  $PreviousVersion = (& $PreviousCommand --version 2>$null | Select-Object -First 1)
  if (-not $PreviousVersion) { Fail 'rollback-verification' 'previous Kungfu did not report a version' }
  New-Item -ItemType Directory -Force -Path $InstallDir, $BinDir | Out-Null
  $OldLauncher = if (Test-Path -LiteralPath $Launcher) { [IO.File]::ReadAllBytes($Launcher) } else { $null }
  try {
    Set-AtomicLauncher $Launcher $PreviousTarget
    Set-AtomicText $CurrentPointer "$PreviousTarget`n"
    $Observed = (& $Launcher --version 2>$null | Select-Object -First 1)
    if ($Observed -ne $PreviousVersion) { Fail 'rollback-verification' "launcher did not report $PreviousVersion" }
    Set-AtomicText $PreviousPointer "$CurrentTarget`n"
  }
  catch {
    Set-AtomicText $CurrentPointer "$CurrentTarget`n"
    if ($OldLauncher) { [IO.File]::WriteAllBytes($Launcher, $OldLauncher) }
    Fail 'rollback-failed' $_.Exception.Message
  }
  Write-Phase 'rollback' "$Launcher -> $PreviousTarget ($PreviousVersion)"
  exit 0
}

$ManagedReceipt = Join-Path $VersionRoot 'install\site-managed-receipt'
if (
  (Test-Path -LiteralPath $ManagedReceipt -PathType Leaf) -and
  ((Get-Content -LiteralPath $ManagedReceipt -Raw).TrimEnd() -eq $ReceiptLine) -and
  ((Read-Pointer $CurrentPointer) -eq $VersionRoot) -and
  (Test-OwnedLauncher $Launcher)
) {
  $InstalledVersion = (& (Join-Path $VersionRoot 'kungfu.cmd') --version 2>$null | Select-Object -First 1)
  if ($InstalledVersion -eq $ExactVersion) {
    Write-Phase 'idempotent' "verified $ExactVersion is already active"
    exit 0
  }
}

function Invoke-ResumableDownload([string]$Uri, [string]$Destination, [int64]$ExpectedSize, [string]$Label) {
  Add-Type -AssemblyName System.Net.Http
  for ($Attempt = 1; $Attempt -le 5; $Attempt += 1) {
    $Offset = if (Test-Path -LiteralPath $Destination) { (Get-Item -LiteralPath $Destination).Length } else { [int64]0 }
    Write-Phase 'download' "$Label attempt $Attempt/5, resume-byte $Offset"
    $Client = New-Object Net.Http.HttpClient
    $Request = New-Object Net.Http.HttpRequestMessage([Net.Http.HttpMethod]::Get, $Uri)
    if ($Offset -gt 0) { $Request.Headers.Range = New-Object Net.Http.Headers.RangeHeaderValue($Offset, $null) }
    try {
      $Response = $Client.SendAsync($Request, [Net.Http.HttpCompletionOption]::ResponseHeadersRead).GetAwaiter().GetResult()
      $Status = [int]$Response.StatusCode
      if ($Offset -gt 0 -and $Status -eq 206) { $Mode = [IO.FileMode]::Append }
      elseif ($Status -eq 200) { $Mode = [IO.FileMode]::Create; $Offset = 0 }
      else { throw "HTTP $Status did not honor a safe complete or Range response" }
      $InputStream = $Response.Content.ReadAsStreamAsync().GetAwaiter().GetResult()
      $OutputStream = New-Object IO.FileStream($Destination, $Mode, [IO.FileAccess]::Write, [IO.FileShare]::Read)
      try {
        $Buffer = New-Object byte[] (1024 * 1024)
        $Transferred = $Offset
        $LastReport = [DateTime]::UtcNow
        while (($Read = $InputStream.Read($Buffer, 0, $Buffer.Length)) -gt 0) {
          $OutputStream.Write($Buffer, 0, $Read)
          $Transferred += $Read
          if (-not $CI -and ([DateTime]::UtcNow - $LastReport).TotalSeconds -ge 1) {
            $Percent = if ($ExpectedSize -gt 0) { [Math]::Min(100, [Math]::Floor(100 * $Transferred / $ExpectedSize)) } else { 0 }
            Write-Progress -Activity "Downloading $Label" -Status "$Transferred / $ExpectedSize bytes" -PercentComplete $Percent
            $LastReport = [DateTime]::UtcNow
          }
        }
      }
      finally {
        if ($OutputStream) { $OutputStream.Dispose() }
        if ($InputStream) { $InputStream.Dispose() }
        if (-not $CI) { Write-Progress -Activity "Downloading $Label" -Completed }
      }
      return
    }
    catch {
      if ($Attempt -ge 5) { Fail 'download-failed' "$Label failed after 5 attempts; partial retained at ${Destination}: $($_.Exception.Message)" }
      $Delay = @(1, 2, 4, 8)[$Attempt - 1]
      Write-Phase 'retry' "$Label failed; retrying in ${Delay}s"
      Start-Sleep -Seconds $Delay
    }
    finally {
      if ($Request) { $Request.Dispose() }
      if ($Response) { $Response.Dispose() }
      if ($Client) { $Client.Dispose() }
    }
  }
}

New-Item -ItemType Directory -Force -Path (Join-Path $InstallDir 'versions'), $BinDir | Out-Null
$Lock = Join-Path $InstallDir '.managed-install.lock'
try { New-Item -ItemType Directory -Path $Lock -ErrorAction Stop | Out-Null }
catch { Fail 'concurrent-install' "another Kungfu installer owns $Lock" }
$Stage = Join-Path $InstallDir ".managed-stage.$([Guid]::NewGuid().ToString('N'))"
try {
  New-Item -ItemType Directory -Path $Stage | Out-Null
  $DownloadRoot = Join-Path $Stage 'download'
  $ExtractRoot = Join-Path $Stage 'extract'
  New-Item -ItemType Directory -Path $DownloadRoot, $ExtractRoot | Out-Null
  $ChannelFile = Join-Path $DownloadRoot 'channel.json'
  Invoke-ResumableDownload $ChannelUrl $ChannelFile 0 'signed channel'
  if ((Get-FileHash -Algorithm SHA256 -LiteralPath $ChannelFile).Hash.ToLowerInvariant() -ne $ChannelSha256) {
    Fail 'channel-byte-mismatch' 'channel bytes differ from the reviewed signed channel'
  }

  $CacheRoot = Join-Path $CacheDir "sha256\$ArtifactDigest"
  $CacheFile = Join-Path $CacheRoot $ArchiveName
  $PartialFile = "$CacheFile.part"
  New-Item -ItemType Directory -Force -Path $CacheRoot | Out-Null
  $CacheValid = $false
  if (Test-Path -LiteralPath $CacheFile -PathType Leaf) {
    $Cached = Get-Item -LiteralPath $CacheFile
    $CachedDigest = (Get-FileHash -Algorithm SHA256 -LiteralPath $CacheFile).Hash.ToLowerInvariant()
    if ($Cached.Length -eq $ArtifactSize -and $CachedDigest -eq $ArtifactDigest) {
      $CacheValid = $true
      Write-Phase 'cache' "verified archive reused from $CacheFile"
    }
    else {
      Move-Item -LiteralPath $CacheFile -Destination "$CacheFile.rejected.$PID"
      Write-Phase 'cache' 'rejected unverified cache entry'
    }
  }
  if (-not $CacheValid) {
    Invoke-ResumableDownload $ArtifactUrl $PartialFile $ArtifactSize 'CLI archive'
    $Partial = Get-Item -LiteralPath $PartialFile
    if ($Partial.Length -ne $ArtifactSize) { Fail 'artifact-size-mismatch' "expected $ArtifactSize bytes, received $($Partial.Length); partial retained at $PartialFile" }
    $ObservedDigest = (Get-FileHash -Algorithm SHA256 -LiteralPath $PartialFile).Hash.ToLowerInvariant()
    if ($ObservedDigest -ne $ArtifactDigest) { Fail 'artifact-digest-mismatch' "archive digest differs; partial retained at $PartialFile" }
    Move-Item -LiteralPath $PartialFile -Destination $CacheFile
    Write-Phase 'cache' "stored verified archive at $CacheFile"
  }

  Write-Phase 'extract' 'validating exact archive closure'
  Add-Type -AssemblyName System.IO.Compression.FileSystem
  $Archive = [IO.Compression.ZipFile]::OpenRead($CacheFile)
  try {
    if ($Archive.Entries.Count -ne $ArchiveEntries) { Fail 'archive-closure-mismatch' "expected $ArchiveEntries entries, observed $($Archive.Entries.Count)" }
    $RootPrefix = "$ArchiveBase/"
    $ExtractFull = [IO.Path]::GetFullPath($ExtractRoot) + [IO.Path]::DirectorySeparatorChar
    $ObservedLinks = 0
    foreach ($Entry in $Archive.Entries) {
      $Name = $Entry.FullName.Replace('\', '/')
      if (
        -not $Name.StartsWith($RootPrefix, [StringComparison]::Ordinal) -or
        $Name.StartsWith('/') -or
        $Name.Split('/') -contains '..' -or
        $Name -match '^[A-Za-z]:'
      ) { Fail 'archive-unsafe' "unsafe archive path: $Name" }
      $Destination = [IO.Path]::GetFullPath((Join-Path $ExtractRoot $Name))
      if (-not $Destination.StartsWith($ExtractFull, [StringComparison]::OrdinalIgnoreCase)) { Fail 'archive-unsafe' "archive path escapes extraction root: $Name" }
      $UnixType = (($Entry.ExternalAttributes -shr 16) -band 0xF000)
      if ($UnixType -eq 0xA000) { $ObservedLinks += 1 }
      elseif ($UnixType -notin @(0, 0x4000, 0x8000)) { Fail 'archive-unsafe' "unsupported archive entry type: $Name" }
    }
    if ($ObservedLinks -ne $ArchiveLinks) { Fail 'archive-closure-mismatch' "expected $ArchiveLinks reviewed links, observed $ObservedLinks" }
  }
  finally { $Archive.Dispose() }
  [IO.Compression.ZipFile]::ExtractToDirectory($CacheFile, $ExtractRoot)
  $Candidate = Join-Path $ExtractRoot $ArchiveBase
  $ProductManifest = Join-Path $Candidate 'product.json'
  $Runtime = Join-Path $Candidate 'runtime\kungfu.exe'
  $CandidateCommand = Join-Path $Candidate 'kungfu.cmd'
  if (-not (Test-Path -LiteralPath $ProductManifest -PathType Leaf)) { Fail 'product-manifest-missing' 'product.json is missing' }
  if (-not (Test-Path -LiteralPath $Runtime -PathType Leaf)) { Fail 'runtime-missing' 'runtime\kungfu.exe is missing' }
  if (-not (Test-Path -LiteralPath $CandidateCommand -PathType Leaf)) { Fail 'runtime-missing' 'kungfu.cmd is missing' }

  Write-Phase 'verify' 'running the Alpha.2 product bootstrap verifier'
  $InstallMetadata = Join-Path $Candidate 'install'
  New-Item -ItemType Directory -Force -Path $InstallMetadata | Out-Null
  $AdapterFile = Join-Path $InstallMetadata 'alpha2-bootstrap-adapter.py'
  $AdapterSource = @'
# SPDX-License-Identifier: Apache-2.0
"""Exact Alpha.2 bridge for the bundled product bootstrap verifier.

The published Alpha.2 channel added two signed ``artifact.name`` fields after
the Alpha.2 CLI archives were built, while those archives also retain their
older combined product platform labels.  The bundled verifier rejects both
representations.  This adapter keeps the original bytes as authority, permits
only those exact field projections in the one reviewed channel root, and
delegates every trust and product check to the bundled
``verify_bootstrap_candidate`` implementation.
"""

from __future__ import annotations

import argparse
import copy
import hashlib
import json
from pathlib import Path
from typing import Any, Mapping

from kungfu import release_channel, runtime_upgrade


ADAPTER_SCHEMA = "kungfu.site-alpha2-bootstrap-adapter/v1"
ADAPTER_RECEIPT_SCHEMA = "kungfu.site-alpha2-bootstrap-adapter-receipt/v1"
CHANNEL_PAYLOAD_ROOT = (
    "sha256:8c031dd420e15ddde5b4e751cb4dcc3c0a2d4bd67956d295918e21165de6abdd"
)
SOURCE_COMMIT = "b0cff8236b8b3746f8028b9d519ed3b0e26096c9"
VERSION = "4.0.0-alpha.2"
ALLOWED_NAMES = {
    (
        "desktop",
        "Kungfu-Episodes-4.0.0-alpha.2-macos-arm64.zip",
        "https://github.com/kungfu-systems/kungfu/releases/download/"
        "v4.0.0-alpha.2/Kungfu-Episodes-4.0.0-alpha.2-macos-arm64.zip",
    ),
    (
        "cli",
        "kungfu-episodes-cli-darwin-arm64.tar.gz",
        "https://github.com/kungfu-systems/kungfu/releases/download/"
        "v4.0.0-alpha.2/kungfu-episodes-cli-darwin-arm64.tar.gz",
    ),
}
ALLOWED_PRODUCTS = {
    ("darwin-arm64", "kungfu-episodes-cli-darwin-arm64.tar.gz"): "darwin",
    ("linux-x64", "kungfu-episodes-cli-linux-x64.tar.gz"): "linux",
    ("windows-x64", "kungfu-episodes-cli-windows-x64.zip"): "win32",
}
SIGNED_MANIFEST_ROOTS = {
    ("darwin", "arm64"): (
        "sha256:96e0a3f78bfa65a8ae06f4fd4bc035cc09211afad499ad6f905a380e1c49d2ae"
    ),
    ("linux", "x64"): (
        "sha256:a81d194ebe7ea874753a66adaa1db6d56121c87cb6e3bf0ae7f6a97045d3a280"
    ),
    ("win32", "x64"): (
        "sha256:094448e272594dce2626fb9d4fe893e2608e700c1a86a5463f2bb3f4e2875551"
    ),
}
BUNDLED_IDENTITY_PROJECTIONS = {
    (
        "darwin",
        "arm64",
        "sha256:3f37f5469e1ebc95d2bb44ba46e259a7bc98e262d7b84f1a51c7fcb9bf79d53c",
    ): SIGNED_MANIFEST_ROOTS[("darwin", "arm64")],
}


class AdapterError(ValueError):
    pass


def canonical_json(value: Any) -> bytes:
    return json.dumps(
        value,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=True,
    ).encode("utf-8")


def content_root(value: Any) -> str:
    return f"sha256:{hashlib.sha256(canonical_json(value)).hexdigest()}"


def read_channel(path: Path) -> dict[str, Any]:
    payload = path.read_bytes()
    try:
        value = json.loads(payload.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as error:
        raise AdapterError("the Alpha.2 channel is not valid JSON") from error
    if not isinstance(value, dict):
        raise AdapterError("the Alpha.2 channel must be an object")
    if value.get("payloadRoot") != CHANNEL_PAYLOAD_ROOT:
        raise AdapterError("the channel is outside the exact Alpha.2 adapter boundary")
    if value.get("sourceCommit") != SOURCE_COMMIT:
        raise AdapterError("the channel source commit differs from Alpha.2")
    return value


def project_manifest(
    manifest: Mapping[str, Any],
    original_validate: Any,
) -> dict[str, Any]:
    value = copy.deepcopy(dict(manifest))
    if value.get("productVersion") != VERSION or value.get("sourceCommit") != SOURCE_COMMIT:
        return original_validate(value)

    removed: set[tuple[str, str, str]] = set()
    artifacts = value.get("artifacts")
    if not isinstance(artifacts, list):
        return original_validate(value)
    for artifact in artifacts:
        if not isinstance(artifact, dict) or "name" not in artifact:
            continue
        coordinate = (artifact.get("kind"), artifact.get("name"), artifact.get("url"))
        if value.get("platform") != "darwin" or value.get("architecture") != "arm64":
            raise AdapterError("artifact.name appeared outside the reviewed Darwin slice")
        if coordinate not in ALLOWED_NAMES:
            raise AdapterError("artifact.name differs from the reviewed Alpha.2 projection")
        removed.add(coordinate)
        del artifact["name"]
    if removed and removed != ALLOWED_NAMES:
        raise AdapterError("the Alpha.2 artifact.name projection is incomplete")
    return original_validate(value)


class CompatibilityJson:
    def __init__(self, delegate: Any) -> None:
        self.delegate = delegate
        self.projected_product = False

    def __getattr__(self, name: str) -> Any:
        return getattr(self.delegate, name)

    def loads(self, payload: Any, *args: Any, **kwargs: Any) -> Any:
        value = self.delegate.loads(payload, *args, **kwargs)
        if not isinstance(value, dict) or value.get("schema") != "kungfu.product.cli/v1":
            return value
        coordinate = (value.get("platform"), value.get("archive"))
        projected_platform = ALLOWED_PRODUCTS.get(coordinate)
        if (
            value.get("product") != "cli"
            or value.get("install", {}).get("source") != "archive"
            or projected_platform is None
        ):
            raise AdapterError("product.json differs from the reviewed Alpha.2 projection")
        projected = copy.deepcopy(value)
        projected["platform"] = projected_platform
        self.projected_product = True
        return projected


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("channel_index", type=Path)
    parser.add_argument("candidate_archive", type=Path)
    parser.add_argument("candidate_root", type=Path)
    parser.add_argument("--channel", required=True)
    parser.add_argument("--platform", required=True, dest="platform_name")
    parser.add_argument("--architecture", required=True)
    parser.add_argument("--version", required=True)
    parser.add_argument("--manifest-root", required=True)
    parser.add_argument("--artifact-root", required=True)
    parser.add_argument("--platform-trust", required=True)
    parser.add_argument("--trusted-key", required=True, action="append")
    parser.add_argument("--adapter-receipt", required=True, type=Path)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    channel = read_channel(args.channel_index)
    if args.version != VERSION or args.channel != "alpha":
        raise AdapterError("the adapter only accepts the exact Alpha.2 alpha channel")
    trusted_keys: dict[str, str] = {}
    for item in args.trusted_key:
        key_id, separator, public_key = item.partition("=")
        if not separator or not key_id or not public_key or key_id in trusted_keys:
            raise AdapterError("trusted key coordinates are invalid")
        trusted_keys[key_id] = public_key

    signed_manifests: dict[tuple[str, str], dict[str, Any]] = {}
    for entry in channel.get("entries", []):
        if not isinstance(entry, dict) or not isinstance(entry.get("manifest"), dict):
            raise AdapterError("the Alpha.2 channel entries are malformed")
        coordinate = (entry.get("platform"), entry.get("architecture"))
        expected_root = SIGNED_MANIFEST_ROOTS.get(coordinate)
        if expected_root is None or entry.get("manifestRoot") != expected_root:
            raise AdapterError("the Alpha.2 signed manifest roots differ from the adapter")
        signed_manifests[coordinate] = entry["manifest"]
    if set(signed_manifests) != set(SIGNED_MANIFEST_ROOTS):
        raise AdapterError("the Alpha.2 signed target closure differs from the adapter")

    original_validate = runtime_upgrade.validate_manifest
    original_release_json = release_channel.json
    compatibility_json = CompatibilityJson(original_release_json)
    projected_bundled_identity = False

    def exact_alpha2_validate(manifest: Mapping[str, Any]) -> dict[str, Any]:
        nonlocal projected_bundled_identity
        bundled_coordinate = (
            manifest.get("platform"),
            manifest.get("architecture"),
            content_root(manifest),
        )
        signed_root = BUNDLED_IDENTITY_PROJECTIONS.get(bundled_coordinate)
        if signed_root is not None:
            coordinate = bundled_coordinate[:2]
            signed_manifest = signed_manifests[coordinate]
            if content_root(signed_manifest) != signed_root:
                raise AdapterError("the signed Alpha.2 identity projection root differs")
            projected_bundled_identity = True
            return project_manifest(signed_manifest, original_validate)
        return project_manifest(manifest, original_validate)

    runtime_upgrade.validate_manifest = exact_alpha2_validate
    release_channel.json = compatibility_json
    try:
        receipt = release_channel.verify_bootstrap_candidate(
            channel_index=args.channel_index,
            trusted_keys=trusted_keys,
            candidate_archive=args.candidate_archive,
            candidate_root=args.candidate_root,
            channel=args.channel,
            platform_name=args.platform_name,
            architecture=args.architecture,
            version=args.version,
            manifest_root=args.manifest_root,
            artifact_root=args.artifact_root,
            platform_trust=args.platform_trust,
        )
    finally:
        runtime_upgrade.validate_manifest = original_validate
        release_channel.json = original_release_json
    if not compatibility_json.projected_product:
        raise AdapterError("the expected Alpha.2 product platform projection was not used")

    adapter_digest = f"sha256:{hashlib.sha256(Path(__file__).read_bytes()).hexdigest()}"
    adapter_receipt = {
        "schema": ADAPTER_RECEIPT_SCHEMA,
        "state": "verified",
        "adapter": {"schema": ADAPTER_SCHEMA, "digest": adapter_digest},
        "compatibilityMode": "signed-alpha2-field-projection",
        "bundledIdentityProjection": projected_bundled_identity,
        "channelPayloadRoot": channel["payloadRoot"],
        "manifestRoot": args.manifest_root,
        "nativeReceiptRoot": receipt["receiptRoot"],
        "platform": args.platform_name,
        "architecture": args.architecture,
        "productVersion": args.version,
    }
    adapter_receipt["receiptRoot"] = content_root(adapter_receipt)
    args.adapter_receipt.write_text(
        json.dumps(adapter_receipt, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    print(json.dumps(receipt, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (AdapterError, OSError, release_channel.ReleaseChannelError) as error:
        raise SystemExit(f"alpha2-bootstrap-adapter: {error}") from error
'@
  [IO.File]::WriteAllText($AdapterFile, "$AdapterSource`n", (New-Object Text.UTF8Encoding($false)))
  if ((Get-FileHash -Algorithm SHA256 -LiteralPath $AdapterFile).Hash.ToLowerInvariant() -ne '4e91a89ec7ffc3f38cf9af6fa38ade062c158d627ca40b04400317948a0ccace') {
    Fail 'product-verification-failed' 'embedded Alpha.2 compatibility adapter digest differs from the catalog'
  }
  $CandidatePython = Join-Path $Candidate 'runtime\python\python.exe'
  if (-not (Test-Path -LiteralPath $CandidatePython -PathType Leaf)) { Fail 'product-verification-failed' 'candidate embedded Python is unavailable' }
  $AdapterReceipt = Join-Path $InstallMetadata 'alpha2-bootstrap-adapter-receipt.json'
  $ReceiptJson = & $CandidatePython $AdapterFile $ChannelFile $CacheFile $Candidate `
    --channel $Channel --platform $Platform --architecture $Architecture --version $ExactVersion `
    --manifest-root $ManifestRoot --artifact-root $ArtifactRoot --platform-trust signed-channel-digest `
    --trusted-key $TrustedKey --adapter-receipt $AdapterReceipt
  if ($LASTEXITCODE -ne 0) { Fail 'product-verification-failed' 'staged Kungfu rejected the signed release identity' }
  [IO.File]::WriteAllText((Join-Path $InstallMetadata 'bootstrap-receipt.json'), (($ReceiptJson -join [Environment]::NewLine) + [Environment]::NewLine), (New-Object Text.UTF8Encoding($false)))
  $CandidateVersion = (& $CandidateCommand --version 2>$null | Select-Object -First 1)
  if ($CandidateVersion -ne $ExactVersion) { Fail 'product-version-mismatch' "staged Kungfu reported '$CandidateVersion'" }
  [IO.File]::WriteAllText((Join-Path $InstallMetadata 'site-managed-receipt'), "$ReceiptLine`n", (New-Object Text.UTF8Encoding($false)))

  if (Test-Path -LiteralPath $VersionRoot) {
    $ExistingReceipt = Join-Path $VersionRoot 'install\site-managed-receipt'
    if (-not (Test-Path -LiteralPath $ExistingReceipt -PathType Leaf) -or (Get-Content -LiteralPath $ExistingReceipt -Raw).TrimEnd() -ne $ReceiptLine) {
      Fail 'installed-content-conflict' "$VersionRoot exists without the exact managed receipt"
    }
    Remove-Item -Recurse -Force -LiteralPath $Candidate
    Write-Phase 'publish' 'verified installed content reused'
  }
  else {
    Move-Item -LiteralPath $Candidate -Destination $VersionRoot
    Write-Phase 'publish' "installed complete archive closure at $VersionRoot"
  }

  $OldCurrent = Read-Pointer $CurrentPointer
  if ($OldCurrent -and -not (Test-OwnedVersion $OldCurrent)) { Fail 'activation-ownership' 'current points outside the managed versions directory' }
  $OldPrevious = Read-Pointer $PreviousPointer
  if ($OldPrevious -and -not (Test-OwnedVersion $OldPrevious)) { Fail 'activation-ownership' 'previous points outside the managed versions directory' }
  $OldLauncher = if (Test-Path -LiteralPath $Launcher) { [IO.File]::ReadAllBytes($Launcher) } else { $null }
  try {
    Set-AtomicLauncher $Launcher $VersionRoot
    Set-AtomicText $CurrentPointer "$VersionRoot`n"
    $Observed = (& $Launcher --version 2>$null | Select-Object -First 1)
    if ($Observed -ne $ExactVersion) { Fail 'activation-verification-failed' "activated launcher did not report $ExactVersion" }
    if ($OldCurrent -and $OldCurrent -ne $VersionRoot) { Set-AtomicText $PreviousPointer "$OldCurrent`n" }
  }
  catch {
    if ($OldCurrent) { Set-AtomicText $CurrentPointer "$OldCurrent`n" } else { Remove-Item -Force -ErrorAction SilentlyContinue -LiteralPath $CurrentPointer }
    if ($OldLauncher) { [IO.File]::WriteAllBytes($Launcher, $OldLauncher) } else { Remove-Item -Force -ErrorAction SilentlyContinue -LiteralPath $Launcher }
    Fail 'activation-failed' "$($_.Exception.Message); prior current was restored"
  }
  Write-Phase 'installed' "$Launcher -> $VersionRoot"
  Write-Host "kungfu-install: PATH, profiles, registry, services, and scheduled tasks were not modified"
  Write-Host "kungfu-install: cache=$CacheFile current=$CurrentPointer previous=$PreviousPointer"
}
finally {
  Remove-Item -Recurse -Force -ErrorAction SilentlyContinue -LiteralPath $Stage
  Remove-Item -Force -ErrorAction SilentlyContinue -LiteralPath $Lock
}
